## 00. PyTorch Fundumentals

Resource notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/

In [ ]:
!nvidea-smi

In [20]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)

2.1.0+cu121


## Introduction to Tensors

### Creatingtensors

PyTorch tensors are created using `torch.Tensor()`=https://pytorch.org/docs/stable/tensors.html

In [ ]:
# Scalar
scalar = torch.tensor(7)
scalar

TypeError: 'int' object is not callable

In [ ]:
scalar.ndim #Can't do this

AttributeError: 'int' object has no attribute 'ndim'

In [ ]:
# Get tensor back as Phython int(Can't do this with scalars anymore)
scalar.item()

AttributeError: 'int' object has no attribute 'item'

In [ ]:
# Vector
vector = torch.tensor([])

На этом моменте я обновил страницу и потерял половину

###Zeros and ones

In [21]:
#Create a taensor of all zeros
zeros = torch.zeros(size=(3,4))
print(zeros)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [22]:
#Create a tensor of all ones
ones = torch.ones(size =(3,4))
print(ones)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [23]:
ones.dtype

torch.float32

###Range of tensors and tensors-like

In [33]:
#use torch.range()
one_to_ten = torch.arange(start=1,end=11,step=1)
print(one_to_ten)

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])


In [36]:
#Creating tensor like
ten_zeros = torch.zeros_like(input=one_to_ten)
print(ten_zeros)

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])
